version: '3'

volumes:
  opt-splunk-etc:
  opt-splunk-var:

services: 
    timescaledb:
        image: prohelion/timescaledb-with-data:0.2
        environment:
            POSTGRES_USER: "teamarrow"
            POSTGRES_PASSWORD: "***REMOVED***"
        ports:
            - 5432:5432
        restart: unless-stopped            
   
    pgadmin:
        image: dpage/pgadmin4:latest
        depends_on:
            - timescaledb
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@teamarrow.com.au"
            PGADMIN_DEFAULT_PASSWORD: "***REMOVED***"
        ports:
            - 5080:80
        restart: unless-stopped

    splunkenterprise:
        hostname: splunkenterprise
        image: splunk/splunk:latest
        environment:
          SPLUNK_START_ARGS: --accept-license --answer-yes --seed-passwd ***REMOVED***
          SPLUNK_ENABLE_LISTEN: 9997
          SPLUNK_ADD: tcp 1514
        volumes:
            - opt-splunk-etc:/opt/splunk/etc
            - opt-splunk-var:/opt/splunk/var
        ports:
            - 8000:8000
            - 9997:9997
            - 8088:8088
            - 8089:8089
            - 9999:9999
            - 1514:1514                   
        
# This will only work on linux as it requires network_mode: host
# For other platforms run the service in SpringBoot locally or Tomcat       
#    telemetry:        
#        image: prohelion/telemetry:0.2-SNAPSHOT
#        depends_on:
#          - timescaledb
#          - splunkenterprise
#        network_mode: "host"          
#        ports:
#          - "9000:9000"        
#          - "4876:4876/udp"        